---
program:
    M.A.R.K
assignments:
    # ==========================================================================
    - name:
          Lab01
      student_submission_directory:
          ./lab02_student-marks
      starter_code_directory:
          ./starter_code
      file_name_pattern:
          UTORID-CSC207-ASSIGNMENTLAB2 # i.e. UTORID-CSC148-ASSIGNMENT#-Result.txt # It is crucial for UTORID and ASSIGNMENT# to be there since they get parsed.
      injection_locations:  # relative to where it would be in the starter code
          - /lab02/src/lab02/PersonTest.java
          - /lab02/src/lab02/SodaCanTest.java

      tests: # things under here needs to be fixed.
          - prep_command: "javac -cp lab02/src/lab02/junit-4.12.jar:"
            marking_command: echo "java -cp lab02/src/lab02/*.java"
            timeout: -1 # if not needed, set as -1
            worth: 0.5  # needs to be between 0 and 1
          - prep_command: javac -cp lab02/src/lab02/*.java
            marking_command: python3 autograder2.py arg1 arg2
            timeout: -1 # if not needed, set as -1
            worth: 0.5   # needs to be between 0 and 1
      creates_analytics_file:
          True/False # it can save it in a txt file ready for usage
      creates_csv_file:
          True/False
does_clean_flag: True/False # burn time full wiping the leftovers?

...
