assignments:
    - a1:
        student_submission_directory:
            - dir_name
        starter_files:
            - dir_name
        tests:
            - test_suite_1:
                prep_commands:
                    - command 1
                    - command 2
                    - command 3
                marking_commands:
                    - test_1:
                        command: python3 tester.py arg1 arg2
                        timeout: 40 #optional
                        worth: 20
                    - test_2:
                        command: python3 tester.py arg1 arg2
                        timeout: 60 #optional
                        worth: 20
        total_worth: val_here
output:
    file_name: filename
    to_percents: True/False # final values to percents as QOL feature.
does_clean_flag: True/False # burn time full wiping the leftovers?
