---
program:
    M.A.R.K
assignments:
    # ==========================================================================
    - name:
          TEST2
      student_submission_directory:
          ./test_2_submissions
          # ./mock_submissions
      starter_code_directory:
          ./starter_code # This test doesn't have a starter code so marking it doesn't need any starter code, just the injections.
      file_name_pattern:
          UTORID-CSC148-ASSIGNMENTNAME-Result.txt
      injection_locations:  # relative to where it would be in the starter code
          # - /test2q1.py
          - /test2q2.py
          # - /test2q3.py
      tests: # things under here needs to be fixed.
          # - prep_command: cd ./ #echo "Running Test 2 Question 1:"
          #   # marking_command: python3 -m doctest -v test2q1.py
          #   marking_command: python3 test2q1_unittest.py
          #   timeout: 6 # if not needed, set as -1
          #   worth: 1  # needs to be between [0,1]
          - prep_command: cd ./ #echo "Running Test 2 Question 2:"
            # marking_command: python3 -m doctest -v test2q2.py
            marking_command: python3 test2q2_unittest.py
            timeout: 6 # if not needed, set as -1
            worth: 1  # needs to be between [0,1]
          # - prep_command: cd ./ #echo "Running Test 2 Question 3:"
          #   # marking_command: python3 -m doctest -v test2q3.py
          #   marking_command: python3 test2q3_unittest.py
          #   timeout: 6 # if not needed, set as -1
          #   worth: 1  # needs to be between [0,1]
      total_worth:
          100
      creates_analytics_file:
          True # it can save it in a txt file ready for usage
      creates_csv_file:
          True # comment
      to_percents:
          False # final values to percents as QOL feature.
    # ==========================================================================
does_clean_flag: False # burn time full wiping the leftovers?

...
